#!/usr/bin/env python3
"""Create or repair the repo-local wiring for decision memory.

A repository opts in by committing ``.agents/memory/config.json``; ``--init``
writes that file with the defaults. Without it this script refuses to wire
anything, and every hook stays silent for the repo.

Idempotent. Creates ``.agents/memory/{adr,notes,local}``, the ADR index, a
managed ``.gitignore`` block, the generated git hooks under ``.githooks/``,
and points ``core.hooksPath`` at them.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from common import (
    ADR_DIR,
    CONFIG_FILE,
    DEFAULT_CONFIG,
    GITHOOKS_DIR,
    LOCAL_DIR,
    NOTES_DIR,
    VERSION,
    dump_json,
    ensure_dir,
    git,
    is_opted_in,
    log,
    read_text,
    repo_root,
    safe_main,
    write_text,
)

HOOK_NAMES: tuple[str, ...] = (
    "pre-commit",
    "post-commit",
    "post-checkout",
    "post-merge",
    "post-rewrite",
)

GITATTRIBUTES_BEGIN: str = "# >>> agentmemory (managed block; do not edit) >>>"
GITATTRIBUTES_END: str = "# <<< agentmemory <<<"
# Note files are append-only, so two branches adding entries to the same day
# produce a conflict git can resolve on its own. `merge=union` is built into
# git; it needs no driver installed, so it works for a teammate who has never
# run install.sh. ADRs are whole files and never want a union merge.
GITATTRIBUTES_ENTRIES: tuple[str, ...] = (f"{NOTES_DIR}/*.md merge=union",)

GITIGNORE_BEGIN: str = "# >>> agentmemory (managed block; do not edit) >>>"
GITIGNORE_END: str = "# <<< agentmemory <<<"
GITIGNORE_ENTRIES: tuple[str, ...] = (f"{GITHOOKS_DIR}/", f"{LOCAL_DIR}/")

AGENTS_BEGIN: str = "<!-- agentmemory:begin (managed block; do not edit) -->"
AGENTS_END: str = "<!-- agentmemory:end -->"
AGENTS_BLOCK: str = f"""{AGENTS_BEGIN}
## Decision memory

This repository keeps its decisions in `.agents/memory/`: ADRs under `adr/`
(the durable, must-obey set) and dated decision notes under `notes/`. Before
changing a subsystem, read the relevant ADRs. When you make a non-obvious
choice, append a note (`Decision`, `Why`, `Alternatives`, `Scope`) to
`.agents/memory/notes/YYYY-MM-DD--<you>.md` and commit it with the change.
With agentmemory installed, the `memory`, `memory-note`, and `adr-promoter`
skills do this for you.
{AGENTS_END}"""

INDEX_INITIAL: str = (
    "# ADR index\n\n"
    "| ADR | Title | Status | Date | Must read |\n"
    "|---|---|---|---|---|\n"
)

_PROVENANCE: str = (
    f"# Generated by agentmemory v{VERSION}. Repaired automatically at session\n"
    "# start when it drifts; do not edit. Uninstall with ./uninstall.sh --repo.\n"
)


def hook_text(name: str) -> str:
    """Return the canonical script for one generated git hook.

    Args:
        name: One of ``HOOK_NAMES``.

    Returns:
        str: Full shell script text.
    """
    head: str = f"#!/usr/bin/env bash\n{_PROVENANCE}set -euo pipefail\n"
    head += 'repo_root="$(git rev-parse --show-toplevel)"\n'
    head += 'scripts="${AGENTMEMORY_SCRIPTS:-$HOME/.agent/shared-repo-memory}"\n'
    if name == "pre-commit":
        return (
            head + 'if [ -f "$scripts/check-memory.py" ]; then\n'
            '  python3 "$scripts/check-memory.py" --repo-root "$repo_root"\n'
            "fi\n"
            'project_hook="$repo_root/scripts/shared-repo-memory/'
            'project-pre-commit.sh"\n'
            'if [ -f "$project_hook" ]; then bash "$project_hook" "$@"; fi\n'
        )
    if name == "post-commit":
        script, label = "commit-capture.py", "commit capture"
        extra = ""
    else:
        script, label = "catchup.py", f"{name} catch-up"
        extra = f" --trigger {name}"
    return (
        head + f'if [ -f "$scripts/{script}" ]; then\n'
        f'  python3 "$scripts/{script}" --repo-root "$repo_root"{extra} '
        f'|| echo "[agentmemory] {label} failed (non-fatal)" >&2\n'
        "fi\n"
    )


def ensure_managed_block(
    path: Path, begin: str, end: str, entries: tuple[str, ...], *, dry_run: bool
) -> bool:
    """Add or refresh a marked block of lines in a config file.

    Args:
        path: File to edit; created when absent.
        begin: Opening marker.
        end: Closing marker.
        entries: Lines the block holds.
        dry_run: Log instead of writing.

    Returns:
        bool: True when the file changed (or would change).
    """
    text: str = read_text(path)
    block: str = "\n".join([begin, *entries, end])
    if block in text:
        return False
    if begin in text and end in text:
        updated = text[: text.index(begin)] + block + text[text.index(end) + len(end) :]
    else:
        sep = (
            ""
            if not text or text.endswith("\n\n")
            else ("\n" if text.endswith("\n") else "\n\n")
        )
        updated = text + sep + block + "\n"
    log(f"{'would update' if dry_run else 'updating'} {path.name} managed block")
    if not dry_run:
        write_text(path, updated)
    return True


def ensure_gitignore(root: Path, *, dry_run: bool) -> bool:
    """Add or refresh the managed ``.gitignore`` block.

    Args:
        root: Repository root.
        dry_run: Log instead of writing.

    Returns:
        bool: True when the file changed (or would change).
    """
    path: Path = root / ".gitignore"
    text: str = read_text(path)
    block: str = "\n".join([GITIGNORE_BEGIN, *GITIGNORE_ENTRIES, GITIGNORE_END])
    if block in text:
        return False
    if GITIGNORE_BEGIN in text and GITIGNORE_END in text:
        start = text.index(GITIGNORE_BEGIN)
        end = text.index(GITIGNORE_END) + len(GITIGNORE_END)
        updated = text[:start] + block + text[end:]
    else:
        sep = (
            ""
            if not text or text.endswith("\n\n")
            else ("\n" if text.endswith("\n") else "\n\n")
        )
        updated = text + sep + block + "\n"
    log(f"{'would update' if dry_run else 'updating'} .gitignore managed block")
    if not dry_run:
        write_text(path, updated)
    return True


def strip_managed_block(path: Path, begin: str, end: str, *, dry_run: bool) -> bool:
    """Remove a marked block from a config file.

    Args:
        path: File to edit.
        begin: Opening marker.
        end: Closing marker.
        dry_run: Log instead of writing.

    Returns:
        bool: True when a block was found.
    """
    text: str = read_text(path)
    if begin not in text or end not in text:
        return False
    updated = (
        text[: text.index(begin)].rstrip("\n")
        + "\n"
        + text[text.index(end) + len(end) :].lstrip("\n")
    ).lstrip("\n")
    log(f"{'would strip' if dry_run else 'stripping'} {path.name} managed block")
    if not dry_run:
        write_text(path, updated if updated.strip() else "")
    return True


def strip_gitignore(root: Path, *, dry_run: bool) -> bool:
    """Remove the managed ``.gitignore`` block.

    Args:
        root: Repository root.
        dry_run: Log instead of writing.

    Returns:
        bool: True when a block was found.
    """
    path: Path = root / ".gitignore"
    text: str = read_text(path)
    if GITIGNORE_BEGIN not in text or GITIGNORE_END not in text:
        return False
    start = text.index(GITIGNORE_BEGIN)
    end = text.index(GITIGNORE_END) + len(GITIGNORE_END)
    updated = (text[:start].rstrip("\n") + "\n" + text[end:].lstrip("\n")).lstrip("\n")
    log(f"{'would strip' if dry_run else 'stripping'} .gitignore managed block")
    if not dry_run:
        write_text(path, updated if updated.strip() else "")
    return True


def agents_file(root: Path) -> Path | None:
    """Return the repo's agent instruction file, preferring AGENTS.md.

    Args:
        root: Repository root.

    Returns:
        Path | None: ``AGENTS.md`` or ``CLAUDE.md`` when one exists.
    """
    for name in ("AGENTS.md", "CLAUDE.md"):
        if (root / name).is_file():
            return root / name
    return None


def ensure_agents_block(root: Path, *, dry_run: bool) -> bool:
    """Add or refresh the managed block in AGENTS.md or CLAUDE.md.

    Only touches a file that already exists; a repo without one gets a hint
    in the log instead of a new top-level file.

    Args:
        root: Repository root.
        dry_run: Log instead of writing.

    Returns:
        bool: True when the file changed (or would change).
    """
    path = agents_file(root)
    if path is None:
        log("no AGENTS.md or CLAUDE.md; add one and rerun to document the convention")
        return False
    text = read_text(path)
    if AGENTS_BLOCK in text:
        return False
    if AGENTS_BEGIN in text and AGENTS_END in text:
        start = text.index(AGENTS_BEGIN)
        end = text.index(AGENTS_END) + len(AGENTS_END)
        updated = text[:start] + AGENTS_BLOCK + text[end:]
    else:
        updated = text.rstrip("\n") + "\n\n" + AGENTS_BLOCK + "\n"
    log(
        f"{'would update' if dry_run else 'updating'} {path.name} decision-memory block"
    )
    if not dry_run:
        write_text(path, updated)
    return True


def strip_agents_block(root: Path, *, dry_run: bool) -> bool:
    """Remove the managed block from AGENTS.md or CLAUDE.md.

    Args:
        root: Repository root.
        dry_run: Log instead of writing.

    Returns:
        bool: True when a block was found.
    """
    path = agents_file(root)
    if path is None:
        return False
    text = read_text(path)
    if AGENTS_BEGIN not in text or AGENTS_END not in text:
        return False
    start = text.index(AGENTS_BEGIN)
    end = text.index(AGENTS_END) + len(AGENTS_END)
    updated = (text[:start].rstrip("\n") + "\n" + text[end:].lstrip("\n")).rstrip(
        "\n"
    ) + "\n"
    log(
        f"{'would strip' if dry_run else 'stripping'} {path.name} decision-memory block"
    )
    if not dry_run:
        write_text(path, updated)
    return True


def ensure_hooks(root: Path, *, dry_run: bool) -> None:
    """Write every generated hook whose content differs from canonical.

    Args:
        root: Repository root.
        dry_run: Log instead of writing.
    """
    for name in HOOK_NAMES:
        path: Path = root / GITHOOKS_DIR / name
        if read_text(path) == hook_text(name):
            continue
        log(f"{'would write' if dry_run else 'writing'} {GITHOOKS_DIR}/{name}")
        if not dry_run:
            write_text(path, hook_text(name))
            path.chmod(path.stat().st_mode | 0o111)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--init",
        action="store_true",
        help=f"opt this repo in by writing {CONFIG_FILE} with the defaults",
    )
    args = parser.parse_args()
    root = repo_root(args.repo_root)
    if root is None:
        log("bootstrap-repo: not inside a git repository")
        return 1
    dry: bool = args.dry_run

    if not is_opted_in(root):
        if not args.init:
            log(
                f"{root} has not opted in to agentmemory (no {CONFIG_FILE}). "
                "Run with --init to opt in."
            )
            return 1
        log(f"{'would write' if dry else 'writing'} {CONFIG_FILE} (opt-in)")
        if not dry:
            dump_json(root / CONFIG_FILE, DEFAULT_CONFIG)

    for rel in (ADR_DIR, NOTES_DIR, LOCAL_DIR):
        if not (root / rel).is_dir():
            log(f"{'would create' if dry else 'creating'} {rel}/")
            if not dry:
                ensure_dir(root / rel)
    index: Path = root / ADR_DIR / "INDEX.md"
    if not index.is_file():
        log(f"{'would create' if dry else 'creating'} {ADR_DIR}/INDEX.md")
        if not dry:
            write_text(index, INDEX_INITIAL)
    ensure_gitignore(root, dry_run=dry)
    ensure_managed_block(
        root / ".gitattributes",
        GITATTRIBUTES_BEGIN,
        GITATTRIBUTES_END,
        GITATTRIBUTES_ENTRIES,
        dry_run=dry,
    )
    ensure_agents_block(root, dry_run=dry)
    ensure_hooks(root, dry_run=dry)
    if git(["config", "--get", "core.hooksPath"], root) != GITHOOKS_DIR:
        log(f"{'would set' if dry else 'setting'} core.hooksPath = {GITHOOKS_DIR}")
        if not dry:
            git(["config", "core.hooksPath", GITHOOKS_DIR], root, check=True)
    log(f"repo wiring {'checked' if dry else 'complete'}: {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(safe_main(main, "bootstrap-repo"))
