#!/usr/bin/env python3
"""Write the memory context into a Cursor rule so Cursor sessions start informed.

Claude Code injects memory through the ``SessionStart`` hook. Cursor has no
equivalent, but it does read ``.cursor/rules/*.mdc`` at the start of a
conversation, so the same bounded block is written there instead.

The file is derived and gitignored, like the catch-up digest: committing it
would conflict on every branch that records a decision, and a teammate's copy
would be stale the moment they pulled. It is rebuilt by the git hooks that
already run after commit, merge, checkout and rewrite, and can be refreshed by
hand at any time.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from common import (
    CURSOR_RULE_RELATIVE,
    build_memory_context,
    is_opted_in,
    log,
    read_text,
    repo_root,
    safe_main,
    write_text,
)

HEADER: str = """---
description: >-
  This repository's architecture decisions and recent decision notes, from
  agentmemory. Read them before changing a subsystem, and record a new
  decision with the memory-note skill when you make a non-obvious choice.
alwaysApply: true
---

<!-- Generated by agentmemory. Not committed: it is rebuilt from
     .agents/memory/ after every commit, merge and checkout. -->

"""


def render(root: Path) -> str:
    """Render the rule file, or an empty string when there is no memory yet.

    Args:
        root: Repository root.

    Returns:
        str: Full rule text.
    """
    context: str = build_memory_context(root)
    return HEADER + context + "\n" if context else ""


def refresh(root: Path) -> Path | None:
    """Write the rule when the repository has memory, remove it when it does not.

    Args:
        root: Repository root.

    Returns:
        Path | None: The rule file when written, else None.
    """
    target: Path = root / CURSOR_RULE_RELATIVE
    text: str = render(root)
    if not text:
        if target.exists():
            target.unlink()
        return None
    if read_text(target) != text:
        write_text(target, text)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=None)
    args = parser.parse_args()
    root = repo_root(args.repo_root)
    if root is None:
        log("cursor-rules: not inside a git repository")
        return 1
    if not is_opted_in(root):
        return 0
    written = refresh(root)
    if written is not None:
        log(f"cursor rule refreshed at {CURSOR_RULE_RELATIVE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(safe_main(main, "cursor-rules"))
